# Ansible playbook AWS - install docker (2021)
---
- name: Install and config Docker in Amazon Linux 2023
  hosts: all
  become: true

  tasks:
    - name: Install dependencies
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - docker
        - python3-pip

    - name: Enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Create group docker
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - docker

    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Add user permissions
      ansible.builtin.shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"

    - name: Install Python SDK
      become: true
      become_user: ec2-user
      ansible.builtin.pip:
        name:
          - requests==2.30.0
          - docker
          - docker-compose
