---
- hosts: ec2
  become_user: ec2-user
  tasks:
    # To prevent the "Error while fetching server API version" Error
    - name: Check if docker is running
      ansible.builtin.service:
        name: docker
        state: started

    - name: Pause for 1 min
      ansible.builtin.pause:
        minutes: 1

    - name: Create Docker Network
      community.docker.docker_network:
        name: wordpress

    - name: Deploy Wordpress Container
      community.docker.docker_container:
        name: wordpress
        image: wordpress:latest
        ports:
          - "80:80"
        networks:
          - name: wordpress
        volumes:
          - wordpress:/var/www/html
        env:
          WORDPRESS_DB_HOST: "rds-endpoint"
          WORDPRESS_DB_USER: "exampleuser"
          WORDPRESS_DB_PASSWORD: "examplepass"
          WORDPRESS_DB_NAME: "wordpressdb"
        restart_policy: always
