# Ansible playbook AWS - install docker (2021)
---
- name: Install and config Docker in Amazon Linux 2023
  hosts: ec2
  become: yes

  tasks:
    - name: Install dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - docker
        - python3-pip

    - name: Enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Create group docker
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - docker

    - name: Restart Docker
      service:
        name: docker
        state: restarted

    - name: Install Python SDK
      become: yes
      become_user: ec2-user
      pip:
        name:
          - docker
          - docker-compose
