name: "Deploy"

run-name: ${{ github.actor }} invoked Terraform & Ansible jobs

on:
  push:
    branches: [test-ci]
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - ".github/workflows/**"
      - "Diagram/**"

env:
  TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "${{ secrets.TF_WORKSPACE }}"
  # Terraform config path to the root module on the repo
  CONFIG_DIRECTORY: "./"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Install AWS CLI"
        uses: unfor19/install-aws-cli-action@v1

      - name: "Run AWS CLI version"
        run: aws --version